### ISSUE TITLE
AVSA

### ISSUE THREAD

**Issue by dharmiks** [vasudevaserver/bibliography#15]
AVSA is doubled here now, one of them should be a songbook AVSAS

**Comment by tejvan** [comment]
I saw the duplication last night. I added the songbook AVSAS. Do you know if songbook has book number?

**Comment by dharmiks** [comment]
I have checked Kakali's list and there is just normal book, no songbook.

**Comment by tejvan** [comment]
I think there is songbook Ten English songs from Aurobindo versus Sri Aurobindo. (2000)
Anyway biblio is correct now.

**Comment by dharmiks** [comment]
OK, just entrytype for Aurobindo versus Sri Aurobindo [songbook] should be changed to Music

**Comment by tejvan** [comment]
done
