### ISSUE TITLE
Rabindranath Tagore: Moon of Bengal's heart

### ISSUE THREAD

**Issue by dharmiks** [vasudevaserver/bibliography#3]
The right title is "Rabindranath Tagore: The Moon of Bengal's heart"
![rtmb](https://cloud.githubusercontent.com/assets/9208648/5874908/27a956de-a307-11e4-898e-06bba82383b3.jpg)

**Comment by tejvan** [comment]
I've corrected in Biblio. I don't see it in seafile/incoming so it must be one of the few books we still need

**Comment by dharmiks** [comment]
OK, I will work on it

**Comment by dharmiks** [comment]
It's done, ready for second check

**Comment by tejvan** [comment]
Thanks Dharmik. Did you add a * for each new page?
 Or should a new page begin with each Title in CAPITAL LETTERS.

for example, is * one page. Or should it be split?

* H

HIMALAYAN BLUNDER
...
HISTORY AND LITERATURE
...

**Comment by dharmiks** [comment]
I prefere combination in a title like
* H -- /Himalayan blunder/
* H -- /History and literature/
or without italic...

**Comment by tejvan** [comment]
I see they are separate pages, because it has been published in large part before. http://www.srichinmoylibrary.com/mother-india-lighthouse-india-spiritual-leaders/bengal-and-bengali-literature-7

**Comment by dharmiks** [comment]
In this case we can keep the same structure...
