### ISSUE TITLE
Rani-da I do know where you live

### ISSUE THREAD

**Issue by dharmiks** [vasudevaserver/bibliography#4]
the right title "Rani-di, I do know where you live"

![rkwl](https://cloud.githubusercontent.com/assets/9208648/5875031/9bfbee92-a308-11e4-813e-d3e89e1226f1.jpg)

**Comment by tejvan** [comment]
thanks. I've updated Biblio. For the moment, I can't see ingestion folder. 

But, would like to spend more time on ingestion. Currently I'm concentrating on existing books to check.

**Comment by tejvan** [comment]
I've updated file name in cataloguing-room/empty-books/paper-books-available

**Comment by dharmiks** [comment]
I don't see this change in cataloguing-room/empty-books/paper-books-available even after my sync.

**Comment by tejvan** [comment]
Could you try again Dharmik?

**Comment by dharmiks** [comment]
Now it is OK
