### ISSUE TITLE
Illumination-experiences on Indian soil, part 1-4

### ISSUE THREAD

**Issue by dharmiks** [vasudevaserver/bibliography#6]
cite-key: IEIS-1 to 4, right cite-keys: IE-1 to 4

**Comment by tejvan** [comment]
Yes. in Biblio IEIS. In book folder IE.

but @priyadarshan IEIS would seem to be correct cite-key?

**Comment by priyadarshan** [comment]
If it is all right with you, I would keep IE, as it is a quite meaningful series, and it seems it will not clash with other more pre-eminent titles.

**Comment by tejvan** [comment]
Thanks. I have updated biblio file
