### ISSUE TITLE
Transcendence-Perfection

### ISSUE THREAD

**Issue by dharmiks** [vasudevaserver/bibliography#9]
biblio cite-key: TRPR, archive cite-key: TRP
songbook: TRPRS

**Comment by tejvan** [comment]
Thanks. It seems best to leave as TRP (like archive). Though we could have had TP

**Comment by tejvan** [comment]
I had to leave songbook at TRPRS because TRPS is taken with 'Transcendence of the past"

**Comment by priyadarshan** [comment]
Since `Transcendence-Perfection` is such a pre-eminent book, perhaps we could indeed consider changing to `TP`?

Songbook could be TPS, but since they are in any case separate titles, a difference would be all right.

**Comment by tejvan** [comment]
I changed to TP and TPS (songbook)

TP will need CITE-KEY updating

**Comment by priyadarshan** [comment]
Done.
